default_dbsi_parameter_maps = {'dti_fa'                     : 'scalar',
                               'dti_cfa'                    : '3-vector',
                               'dti_axial'                  : 'scalar',
                               'dti_radial'                 : 'scalar',
                               'dti_adc'                    : 'scalar',
                               'dti_lambda_1'               : 'scalar',
                               'dti_lambda_2'               : 'scalar',
                               'dti_lambda_3'               : 'scalar',
                               'dti_eigenvec_1'             : '3-vector',
                               'dti_eigenvec_2'             : '3-vector',
                               'dti_eigenvec_3'             : '3-vector',
                               'dti_eigenvec_1_cfa'         : '3-vector',
                               'dti_eigenvec_2_cfa'         : '3-vector',
                               'dti_eigenvec_3_cfa'         : '3-vector',
                               'isotropic_adc'              : 'scalar',
                               'isotropic_fraction'         : 'scalar',
                               'b0_map'                     : 'scalar'}

three_seg_iso_maps     = {'restricted_adc'             : 'scalar', 
                          'restricted_fraction'        : 'scalar',
                          'hindered_fraction'          : 'scalar',
                          'hindered_adc'               : 'scalar',
                          'water_fraction'             : 'scalar',
                          'water_adc'                  : 'scalar'}

four_seg_iso_maps     = { 'highly_restricted_adc'      : 'scalar', 
                          'highly_restricted_fraction' : 'scalar',
                          'restricted_adc'             : 'scalar', 
                          'restricted_fraction'        : 'scalar',
                          'hindered_fraction'          : 'scalar',
                          'hindered_adc'               : 'scalar',
                          'water_fraction'             : 'scalar',
                          'water_adc'                  : 'scalar'}

default_expanded_fiber_maps = {
                          'fiber_0d_fraction'         : 'scalar',
                          'fiber_0d_fa'               : 'scalar',
                          'fiber_0d_axial'            : 'scalar',
                          'fiber_0d_radial'           : 'scalar',
                          'fiber_0d_adc'              : 'scalar',
                          'fiber_0d_cfa'              : '3-vector',
                          'fiber_0d_lambda_1'         : 'scalar',
                          'fiber_0d_lambda_2'         : 'scalar',
                          'fiber_0d_lambda_3'         : 'scalar',
                          'fiber_0d_eigenvec_1'       : '3-vector',
                          'fiber_0d_eigenvec_2'       : '3-vector',
                          'fiber_0d_eigenvec_3'       : '3-vector',
                          'fiber_0d_eigenvec_1_cfa'   : '3-vector',
                          'fiber_0d_eigenvec_2_cfa'   : '3-vector',
                          'fiber_0d_eigenvec_3_cfa'   : '3-vector',
                          
                          'fiber_0d_IA_fraction'       : 'scalar',
                          'fiber_0d_IA_fa'             : 'scalar',
                          'fiber_0d_IA_axial'          : 'scalar',
                          'fiber_0d_IA_radial'         : 'scalar',
                          'fiber_0d_IA_adc'            : 'scalar',
                          'fiber_0d_IA_lambda_1'       : 'scalar',
                          'fiber_0d_IA_lambda_2'       : 'scalar',
                          'fiber_0d_IA_lambda_3'       : 'scalar',
                          'fiber_0d_IA_eigenvec_1'     : '3-vector',
                          'fiber_0d_IA_eigenvec_2'     : '3-vector',
                          'fiber_0d_IA_eigenvec_3'     : '3-vector',
                          'fiber_0d_IA_eigenvec_1_cfa' : '3-vector',
                          'fiber_0d_IA_eigenvec_2_cfa' : '3-vector',
                          'fiber_0d_IA_eigenvec_3_cfa' : '3-vector',

                          'fiber_0d_EA_fraction'         : 'scalar',
                          'fiber_0d_EA_fa'               : 'scalar',
                          'fiber_0d_EA_axial'            : 'scalar',
                          'fiber_0d_EA_radial'           : 'scalar',
                          'fiber_0d_EA_adc'              : 'scalar',
                          'fiber_0d_EA_lambda_1'         : 'scalar',
                          'fiber_0d_EA_lambda_2'         : 'scalar',
                          'fiber_0d_EA_lambda_3'         : 'scalar',
                          'fiber_0d_EA_eigenvec_1'       : '3-vector',
                          'fiber_0d_EA_eigenvec_2'       : '3-vector',
                          'fiber_0d_EA_eigenvec_3'       : '3-vector',
                          'fiber_0d_EA_eigenvec_1_cfa'   : '3-vector',
                          'fiber_0d_EA_eigenvec_2_cfa'   : '3-vector',
                          'fiber_0d_EA_eigenvec_3_cfa'   : '3-vector',
           
                          'dti_fa'                    : 'scalar',
                          'dti_cfa'                   : '3-vector',
                          'dti_axial'                 : 'scalar',
                          'dti_radial'                : 'scalar',
                          'dti_adc'                   : 'scalar',
                          'dti_lambda_1'              : 'scalar',
                          'dti_lambda_2'              : 'scalar',
                          'dti_lambda_3'              : 'scalar',
                          'dti_eigenvec_1'            : '3-vector',
                          'dti_eigenvec_2'            : '3-vector',
                          'dti_eigenvec_3'            : '3-vector',
                          'dti_eigenvec_1_cfa'        : '3-vector',
                          'dti_eigenvec_2_cfa'        : '3-vector',
                          'dti_eigenvec_3_cfa'        : '3-vector'
                         }


